require('hidpi-canvas/dist/hidpi-canvas');
require("font-awesome-webpack");
import '../app/style.css';
import '../app/mainController';
import '../app/detailController';
import '../app/pagesController';
import '../app/searchController';
import '../app/navigationController';
import '../app/genresController';
import '../app/genreController';
